package com.cohida.JudokaRegister.Enums;

import java.util.Arrays;

public enum Countries {
    AFGHANISTAN(1, "Afghanistan"),
    ALBANIA(2, "Albania"),
    ALGERIA(3, "Algeria"),
    ANDORRA(4, "Andorra"),
    ANGOLA(5, "Angola"),
    ANTIGUA_AND_BARBUDA(6, "Antigua and Barbuda"),
    ARGENTINA(7, "Argentina"),
    ARMENIA(8, "Armenia"),
    AUSTRALIA(9, "Australia"),
    AUSTRIA(10, "Austria"),
    AZERBAIJAN(11, "Azerbaijan"),
    BAHAMAS(12, "Bahamas"),
    BAHRAIN(13, "Bahrain"),
    BANGLADESH(14, "Bangladesh"),
    BARBADOS(15, "Barbados"),
    BELARUS(16, "Belarus"),
    BELGIUM(17, "Belgium"),
    BELIZE(18, "Belize"),
    BENIN(19, "Benin"),
    BHUTAN(20, "Bhutan"),
    BOLIVIA(21, "Bolivia"),
    BOSNIA_AND_HERZEGOVINA(22, "Bosnia and Herzegovina"),
    BOTSWANA(23, "Botswana"),
    BRAZIL(24, "Brazil"),
    BRUNEI(25, "Brunei"),
    BULGARIA(26, "Bulgaria"),
    BURKINA_FASO(27, "Burkina Faso"),
    BURUNDI(28, "Burundi"),
    CABO_VERDE(29, "Cabo Verde"),
    CAMBODIA(30, "Cambodia"),
    CAMEROON(31, "Cameroon"),
    CANADA(32, "Canada"),
    CENTRAL_AFRICAN_REPUBLIC(33, "Central African Republic"),
    CHAD(34, "Chad"),
    CHILE(35, "Chile"),
    CHINA(36, "China"),
    COLOMBIA(37, "Colombia"),
    COMOROS(38, "Comoros"),
    CONGO_DEMOCRATIC_REPUBLIC(39, "Democratic Republic of the Congo"),
    CONGO_REPUBLIC(40, "Republic of the Congo"),
    COSTA_RICA(41, "Costa Rica"),
    CROATIA(42, "Croatia"),
    CUBA(43, "Cuba"),
    CYPRUS(44, "Cyprus"),
    CZECH(45, "Czech Republic"),
    DENMARK(46, "Denmark"),
    DJIBOUTI(47, "Djibouti"),
    DOMINICA(48, "Dominica"),
    DOMINICAN_REPUBLIC(49, "Dominican Republic"),
    EAST_TIMOR(50, "East Timor"),
    ECUADOR(51, "Ecuador"),
    EGYPT(52, "Egypt"),
    EL_SALVADOR(53, "El Salvador"),
    EQUATORIAL_GUINEA(54, "Equatorial Guinea"),
    ERITREA(55, "Eritrea"),
    ESTONIA(56, "Estonia"),
    ESWATINI(57, "Eswatini"),
    ETHIOPIA(58, "Ethiopia"),
    FIJI(59, "Fiji"),
    FINLAND(60, "Finland"),
    FRANCE(61, "France"),
    GABON(62, "Gabon"),
    GAMBIA(63, "Gambia"),
    GEORGIA(64, "Georgia"),
    GERMANY(65, "Germany"),
    GHANA(66, "Ghana"),
    GREECE(67, "Greece"),
    GRENADA(68, "Grenada"),
    GUATEMALA(69, "Guatemala"),
    GUINEA(70, "Guinea"),
    GUINEA_BISSAU(71, "Guinea-Bissau"),
    GUYANA(72, "Guyana"),
    HAITI(73, "Haiti"),
    HONDURAS(74, "Honduras"),
    HUNGARY(75, "Hungary"),
    ICELAND(76, "Iceland"),
    INDIA(77, "India"),
    INDONESIA(78, "Indonesia"),
    IRAN(79, "Iran"),
    IRAQ(80, "Iraq"),
    IRELAND(81, "Ireland"),
    ISRAEL(82, "Israel"),
    ITALY(83, "Italy"),
    IVORY_COAST(84, "Ivory Coast"),
    JAMAICA(85, "Jamaica"),
    JAPAN(86, "Japan"),
    JORDAN(87, "Jordan"),
    KAZAKHSTAN(88, "Kazakhstan"),
    KENYA(89, "Kenya"),
    KIRIBATI(90, "Kiribati"),
    KOREA_NORTH(91, "North Korea"),
    KOREA_SOUTH(92, "South Korea"),
    KOSOVO(93, "Kosovo"),
    KUWAIT(94, "Kuwait"),
    KYRGYZSTAN(95, "Kyrgyzstan"),
    LAOS(96, "Laos"),
    LATVIA(97, "Latvia"),
    LEBANON(98, "Lebanon"),
    LESOTHO(99, "Lesotho"),
    LIBERIA(100, "Liberia"),
    LIBYA(101, "Libya"),
    LIECHTENSTEIN(102, "Liechtenstein"),
    LITHUANIA(103, "Lithuania"),
    LUXEMBOURG(104, "Luxembourg"),
    MADAGASCAR(105, "Madagascar"),
    MALAWI(106, "Malawi"),
    MALAYSIA(107, "Malaysia"),
    MALDIVES(108, "Maldives"),
    MALI(109, "Mali"),
    MALTA(110, "Malta"),
    MARSHALL_ISLANDS(111, "Marshall Islands"),
    MAURITANIA(112, "Mauritania"),
    MAURITIUS(113, "Mauritius"),
    MEXICO(114, "Mexico"),
    MICRONESIA(115, "Micronesia"),
    MOLDOVA(116, "Moldova"),
    MONACO(117, "Monaco"),
    MONGOLIA(118, "Mongolia"),
    MONTENEGRO(119, "Montenegro"),
    MOROCCO(120, "Morocco"),
    MOZAMBIQUE(121, "Mozambique"),
    MYANMAR(122, "Myanmar"),
    NAMIBIA(123, "Namibia"),
    NAURU(124, "Nauru"),
    NEPAL(125, "Nepal"),
    NETHERLANDS(126, "Netherlands"),
    NEW_ZEALAND(127, "New Zealand"),
    NICARAGUA(128, "Nicaragua"),
    NIGER(129, "Niger"),
    NIGERIA(130, "Nigeria"),
    NORTH_MACEDONIA(131, "North Macedonia"),
    NORWAY(132, "Norway"),
    OMAN(133, "Oman"),
    PAKISTAN(134, "Pakistan"),
    PALAU(135, "Palau"),
    PALESTINE(136, "Palestine"),
    PANAMA(137, "Panama"),
    PAPUA_NEW_GUINEA(138, "Papua New Guinea"),
    PARAGUAY(139, "Paraguay"),
    PERU(140, "Peru"),
    PHILIPPINES(141, "Philippines"),
    POLAND(142, "Poland"),
    PORTUGAL(143, "Portugal"),
    QATAR(144, "Qatar"),
    ROMANIA(145, "Romania"),
    RUSSIA(146, "Russia"),
    RWANDA(147, "Rwanda"),
    SAINT_KITTS_AND_NEVIS(148, "Saint Kitts and Nevis"),
    SAINT_LUCIA(149, "Saint Lucia"),
    SAINT_VINCENT_AND_THE_GRENADINES(150, "Saint Vincent and the Grenadines"),
    SAMOA(151, "Samoa"),
    SAN_MARINO(152, "San Marino"),
    SAO_TOME_AND_PRINCIPE(153, "Sao Tome and Principe"),
    SAUDI_ARABIA(154, "Saudi Arabia"),
    SENEGAL(155, "Senegal"),
    SERBIA(156, "Serbia"),
    SEYCHELLES(157, "Seychelles"),
    SIERRA_LEONE(158, "Sierra Leone"),
    SINGAPORE(159, "Singapore"),
    SLOVAKIA(160, "Slovakia"),
    SLOVENIA(161, "Slovenia"),
    SOLOMON_ISLANDS(162, "Solomon Islands"),
    SOMALIA(163, "Somalia"),
    SOUTH_AFRICA(164, "South Africa"),
    SOUTH_SUDAN(165, "South Sudan"),
    SPAIN(166, "Spain"),
    SRI_LANKA(167, "Sri Lanka"),
    SUDAN(168, "Sudan"),
    SURINAME(169, "Suriname"),
    SWEDEN(170, "Sweden"),
    SWITZERLAND(171, "Switzerland"),
    SYRIA(172, "Syria"),
    TAIWAN(173, "Taiwan"),
    TAJIKISTAN(174, "Tajikistan"),
    TANZANIA(175, "Tanzania"),
    THAILAND(176, "Thailand"),
    TOGO(177, "Togo"),
    TONGA(178, "Tonga"),
    TRINIDAD_AND_TOBAGO(179, "Trinidad and Tobago"),
    TUNISIA(180, "Tunisia"),
    TURKEY(181, "Turkey"),
    TURKMENISTAN(182, "Turkmenistan"),
    TUVALU(183, "Tuvalu"),
    UGANDA(184, "Uganda"),
    UKRAINE(185, "Ukraine"),
    UNITED_ARAB_EMIRATES(186, "United Arab Emirates"),
    UNITED_KINGDOM(187, "United Kingdom"),
    UNITED_STATES(188, "United States"),
    URUGUAY(189, "Uruguay"),
    UZBEKISTAN(190, "Uzbekistan"),
    VANUATU(191, "Vanuatu"),
    VATICAN(192, "Vatican City"),
    VENEZUELA(193, "Venezuela"),
    VIETNAM(194, "Vietnam"),
    YEMEN(195, "Yemen"),
    ZAMBIA(196, "Zambia"),
    ZIMBABWE(197, "Zimbabwe");

    private final int id;
    private final String displayName;

    Countries(int id, String displayName) {
        this.id = id;
        this.displayName = displayName;
    }

    public int getId() {
        return id;
    }

    public String getDisplayName() {
        return displayName;
    }

    public static Countries fromId(Integer id) {
        if (id == null) return null;
        return Arrays.stream(values())
                .filter(e -> e.getId() == (id))
                .findFirst()
                .orElseThrow(() -> new IllegalArgumentException("Invalid country ID: " + id));
    }

    public static Countries fromName(String name) {
        try {
            return Countries.valueOf(name.toUpperCase().replace(" ", "_"));
        } catch (IllegalArgumentException e) {
            return null;
        }
    }
}